### ISSUE TITLE
Login qilayotganda token xatoligi kursatilmayapti

### ISSUE THREAD

**Issue by shohruxsaidov** [ashomurodov/vueLibrary#3]
Hozirgi holati:
Agarda token invalid bo'lsa va submit knopkasi bosilsa hech qanaqa reaksiya ko'rsatilmayapti

Kutilgan holati:
Tokenni xato kiritligani haqida xato kursatilishi kk (input tagida tekst ko'rinishida )

**Comment by ashomurodov** [comment]
To'g'rlandi endilikda xato kiritsa input qizarib error message pasida chiqib turadi
